### ISSUE TITLE
Parallelize likelihood computation

### ISSUE THREAD

**Issue by matsen** [matsengrp/libsbn#41]
At first I thought that we could do this simply with C++'s built in parallel loops, etc, but we'll need to think a little about how that will work. 

If we want k threads I'd think that we'd want to initialize k BEAGLE instances and then send trees to the various instances on various threads. I think this is worth the programming effort?

**Comment by matsen** [comment]
This looks good https://stackoverflow.com/questions/19125371/how-do-i-asynchronously-map-values-onto-a-function-with-threading but doesn't limit the number of execution threads.
Here's a sketch of how to do that: https://www.reddit.com/r/cpp_questions/comments/5ih1g8/how_do_i_limit_the_number_of_threads_used_by/
The only relevant thing I could find in https://www.amazon.com/C-Concurrency-Action-Practical-Multithreading/dp/1933988770 was this, demonstrating how to get the number of threads at runtime. 

![image](https://user-images.githubusercontent.com/112708/60882929-b65f2f80-a1fd-11e9-9a3f-8d1d89b788c9.png)

**Comment by 4ment** [comment]
Are you planning to parallelize across sites? If yes BEAGLE3 can do it for you 

> Specifically, we have added an implementation for multicore CPUs that uses a pool of C++ threads  to process independent site patterns concurrently

Another way would be to calculate the gradient of one branch length on a single thread. Once the 2 sets of partial likelihoods are calculated (that's the postorder followed by the preorder calculations), every gradient can be calculated efficiently and independently.
