### ISSUE TITLE
Expose branch lengths to Numpy

### ISSUE THREAD

**Issue by christiaanjs** [matsengrp/libsbn#68]
One initial manner external modelling/inference tools could interact with libsbn is by using it to calculate the phylogenetic likelihood. Doing this in Numpy-based tools (e.g. PyMC3) requires:
* Exposing branch lengths as a mutable array
* Exposing topology structure in an array-based data structure (e.g. an array of parent indices)

**Comment by matsen** [comment]
My suggestion is to not only expose a topology, but also be able to load in a topology via an array.
